### base url

GET http://localhost:3000

### get all users

GET http://localhost:3000/api/users

### get all products

GET http://localhost:3000/api/products

### get a single user by id

GET http://localhost:3000/api/users/1

### get users with query params

GET http://localhost:3000/api/users?filter=name&value=ja

### post a new user

POST http://localhost:3000/api/users
Content-Type: application/json

 {
     "name": "alice",
     "displayName": "alice wonderland"
 }
