### base url

GET http://localhost:3000

### get all users

GET http://localhost:3000/api/users

### get all products

GET http://localhost:3000/api/products

### get a single user by id

GET http://localhost:3000/api/users/3

### get users with query params

GET http://localhost:3000/api/users?filter=name&value=ja

### post a new user

POST http://localhost:3000/api/users
Content-Type: application/json

 {
     "name": "mona",
     "displayName": "mona lilly",
     "password":"lilly127655"
 }

### update a single user

PUT http://localhost:3000/api/users/1
Content-Type: application/json

{
    "name": "coco",
    "displayName": "mr coco"
}


### update a single user partially

PATCH http://localhost:3000/api/users/1
Content-Type: application/json

{
    "displayName": "coco the great"
}


### delete a user

DELETE http://localhost:3000/api/users/3

### get users with query params validation failed

GET http://localhost:3000/api/users?filter=n&value=ja

### authenticate a user

POST http://localhost:3000/api/auth
Content-Type: application/json

{
    "name": "mona",
    "password":"lilly127655"
}

### get authentication status

GET http://localhost:3000/api/auth/status


### add item to cart

POST http://localhost:3000/api/cart
Content-Type: application/json

{
    "name": "chicken breast",
    "price": 100
}

### see the cart items

GET http://localhost:3000/api/cart

### log out a user

POST http://localhost:3000/api/auth/logout
Content-Type: application/json

{}

